server:
  port: 12809
  servlet:
    context-path: /workbench

mybatis:
  mapper-locations: classpath:mybatis-mapper/*.xml
  type-aliases-package: com.xxl.job.workbench.dao
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/workbench?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&serverTimezone=GMT
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: defaultConsumerGroup
