server:
  port: 12809
  servlet:
    context-path: /workbench

mybatis:
  mapper-locations: classpath:mybatis-mapper/*.xml
  type-aliases-package: com.xxl.job.workbench.dao
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/workbench?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&serverTimezone=GMT
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: master:9092,slave1:9092,slave2:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 生产者每个批次最多提交多少条数据
      batch-size: 16384
      # 生产者一端总的可用发送缓冲区大小，为32MB
      buffer-memory: 33554432
    consumer:
      # 消费组ID
      group-id: defaultConsumerGroup
      # 如果在当前kafka中找不到当前offset，就读取最早的
      auto-offset-reset: earliest
      # 自动提交偏移量
      enable-auto-commit: true
      # offset自动提交的时间间隔
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
dubbo:
  protocol:
    name: dubbo
    port: 20881
  application:
    name: demo-consumer # 消息者名字
  registry:
    address: zookeeper://master:2181?backup=slave1:2181,slave2:2181